#pragma config(Sensor, in1,    leftTapeFinder, sensorLineFollower)
#pragma config(Sensor, in2,    rightTapeFinder, sensorLineFollower)
#pragma config(Sensor, in3,    distanceFinder, sensorPotentiometer)
#pragma config(Sensor, dgtl1,  proximitySensor, sensorSONAR_cm)
#pragma config(Motor,  port2,           swivelWheel,   tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftWheel,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightWheel,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//RobotAttribs.
int StartUpTimeMsec = 2000;

//PinMovement
int minTapeValue = 1000;
int circleCount = 0;
int totalNumberOfCircles = 3;
int turnTimeMsec = 1500;

//Speeds
int steadySpeed = 30;
int fasterSpeed = 60;

void pinManuver(int speed) {
	if (SensorValue(leftTapeFinder) < minTapeValue && SensorValue(rightTapeFinder) < minTapeValue) {
		motor[swivelWheel] = 0;
		motor[leftWheel] = speed;
		motor[rightWheel] = speed;
	}
	else if (SensorValue(leftTapeFinder) >= minTapeValue && SensorValue(rightTapeFinder) < minTapeValue) {
		motor[swivelWheel] = 90;
		motor[leftWheel] = 0;
		motor[rightWheel] = speed;
	}
	else if (SensorValue(leftTapeFinder) < minTapeValue && SensorValue(rightTapeFinder) >= minTapeValue) {
		motor[swivelWheel] = 90;
		motor[leftWheel] = speed;
		motor[rightWheel] = 0;
	}
	else if (SensorValue(leftTapeFinder) >= minTapeValue && SensorValue(rightTapeFinder) >= minTapeValue) {
		motor[swivelWheel] = 90;
		motor[leftWheel] = speed;
		motor[rightWheel] = speed;
		circleCount += 1;
	}
}

void pinTurn(int timeInMsec) {
	motor[swivelWheel] = 90;
	motor[leftWheel] = 30;
	motor[rightWheel] = 0;
	wait1Msec(timeInMsec);
}

void task_1() {
	if (circleCount != totalNumberOfCircles) {
		pinManuver(steadySpeed);
	}
	else if (circleCount == totalNumberOfCircles) {
		motor[swivelWheel] = 0;
		motor[leftWheel] = 0;
		motor[rightWheel] = 0;
	}
}
void task_2() {
	for(int i = 0; i = 2; i++) {
		if (circleCount == 0) {
			motor[leftWheel] = steadySpeed;
			motor[rightWheel] = steadySpeed;
		}
		else if (circleCount != totalNumberOfCircles) {
			pinManuver(steadySpeed);
		}
		else if (circleCount == totalNumberOfCircles) {
			motor[swivelWheel] = 0;
			motor[leftWheel] = 0;
			motor[rightWheel] = 0;
			wait1Msec(5000);
			pinTurn(turnTimeMsec);
			circleCount = 0;
		}
	}
}
void task_3() {
	//TBC
}

task main() {

	//writeDebugStream("Int i is : %d", SensorValue[leftTapeFinder]);
	//writeDebugStream("Int i is : %d", SensorValue[rightTapeFinder]);

	wait1Msec(StartUpTimeMsec);
	task_1();
	task_2();
	task_3();
}
