#pragma config(Sensor, in1,    leftTapeFinder, sensorLineFollower)
#pragma config(Sensor, in2,    rightTapeFinder, sensorLineFollower)
#pragma config(Sensor, in3,    distanceFinder, sensorPotentiometer)
#pragma config(Motor,  port2,           swivelWheel,   tmotorVex269_MC29, openLoop)
#pragma config(Motor,  port3,           leftWheel,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           rightWheel,    tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
bool circleCheck = false;
int minTapeValue = 1000;

void task1_CircleCheckComplete() {
 if (SensorValue(leftTapeFinder) < minTapeValue && SensorValue(rightTapeFinder) < minTapeValue) {
	motor[swivelWheel] = 0;
	motor[leftWheel] = 30;
	motor[rightWheel] = 30;
	circleCheck = false;
	}
else if (SensorValue(leftTapeFinder) >= minTapeValue && SensorValue(rightTapeFinder) < minTapeValue) {
	motor[swivelWheel] = 90;
	motor[leftWheel] = 0;
	motor[rightWheel] = 30;
	circleCheck = false;
	}
else if (SensorValue(leftTapeFinder) < minTapeValue && SensorValue(rightTapeFinder) >= minTapeValue) {
	motor[swivelWheel] = 90;
	motor[leftWheel] = 30;
	motor[rightWheel] = 0;
	circleCheck = false;
	}
else if (SensorValue(leftTapeFinder) >= minTapeValue && SensorValue(rightTapeFinder) >= minTapeValue) {
	motor[swivelWheel] = 90;
	motor[leftWheel] = 0;
	motor[rightWheel] = 0;
	circleCheck = true;
	}
}

task main() {
writeDebugStream("Int i is : %d", SensorValue[leftTapeFinder]);
writeDebugStream("Int i is : %d",
SensorValue[rightTapeFinder]);
/*
int circleCount = 0;

motor[swivelWheel] = 0;
motor[leftWheel] = 0;
motor[rightWheel] = 0;

wait1Msec(2000);

if (circleCheck) {
	circleCount += 1;
}

task1_CircleCheckComplete();

if (circleCount == 3) {
	motor[swivelWheel] = 0;
	motor[leftWheel] = 0;
	motor[rightWheel] = 0;
}
*/

}
